<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cx</string>
	</array>
	<key>name</key>
	<string>Cortex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"([^\\"]|\\\\|\\")*\"</string>
			<key>name</key>
			<string>string.quoted.double.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|while|switch|case|default|break|try|catch)\b</string>
			<key>name</key>
			<string>keyword.control.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(on|update|declare|define|destruct|scope|self)\b</string>
			<key>name</key>
			<string>keyword.control.event.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(void|object|any)\b</string>
			<key>name</key>
			<string>storage.type.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(boolean|binary|character|int|uint|float|enum|bitmask|text)\b</string>
			<key>name</key>
			<string>storage.type.primitive.base.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(octet|word|bool|char|uint8|uint16|uint32|uint64|int8|int16|int32|int64|float32|float64|string)\b</string>
			<key>name</key>
			<string>storage.type.primitive.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(interface|struct|class|member)\b</string>
			<key>name</key>
			<string>storage.type.interface.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(collection|array|sequence|list|map)\b</string>
			<key>name</key>
			<string>storage.type.collection.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function|method|virtual|delegate|callback|observer)\b</string>
			<key>name</key>
			<string>storage.type.procedure.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var)\b</string>
			<key>name</key>
			<string>storage.modifier.cortex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:|\;|(|)|\[|\]|\.|\{|\}|,|\+|-|\*|/|%|\+\+|--|!|&amp;|~|&lt;|&gt;|\?|&lt;=|&gt;=|==|!=|\||\^|\|\||&amp;&amp;|=|\*=|/=|\+=|-=|\|=|&amp;=|\:\:|\:\:\:|-&gt;|&lt;-|&lt;&lt;|&gt;&gt;|@|`|\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.cortex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cortex</string>
	<key>uuid</key>
	<string>5c7db884-27a2-4eaa-a18b-0cd7fa9b0c5e</string>
</dict>
</plist>
